# Introduction

The following Bylaws are designed to help our church operate in a Biblically faithful manner. Like most church bylaws, they cover basic issues related to membership, congregational meetings, the responsibilities of church officers, and the use of church property. They also cover issues that are often overlooked in standard bylaws, such as Biblical counseling, confidentiality, and conflict resolution.

At first glance, you may wonder why we have gone into such detail and addressed issues that churches have traditionally ignored. The primary answer to this question is that we believe there has been a significant change in the moral and legal climate of this country. Historically, most Americans, whether they were Christian or not, held to a common framework of basic moral values. Honesty, fairness, respect for others, self-discipline, sexual fidelity, and accountability were generally viewed as commendable qualities. In recent years, however, respect for these qualities has been undermined by a growing emphasis on individualism, a diminished respect for authority, the acceptance of relative morality, and the loss of common norms and values.

Because of this change, it is no longer possible to assume that everyone holds to the same standard of common sense, fairness, and justice, even within the same church. Therefore, what seems to be appropriate to one member of a church (for example, giving three days' notice of a special congregational meeting, or allowing the deacons to spend \$3,000 without congregational approval) might seem to be outrageous to another member.

This loss of common values even within the church can cause a great deal of confusion and conflict. It can also expose a church to devastating lawsuits. A generation ago, very few people would have even dreamed of suing a church. But the legal climate has changed dramatically in recent years, and today lawsuits against churches are commonplace. Part of the reason for this is that people have differing expectations as to how a church should conduct its affairs and treat its members. When these expectations are not met, a lawsuit often follows, which can ruin a church both spiritually and financially.

As Proverbs 22:3 warns, "A prudent man sees danger and takes refuge, but the simple keep going and suffer for it." Realizing that the absence of common norms and values can pose a threat to the unity and well-being of our church, we developed these Bylaws as a means of establishing commonly accepted standards for how we would treat one another and govern ourselves as a body. In particular, these Bylaws are designed to accomplish these goals:

- They help to prevent surprises and disappointed expectations by providing potential members with a thorough explanation of how the church intends to govern itself.

- They reduce the likelihood of confusion and conflict within the church by establishing clear operational guidelines.

- They prevent the misuse of authority by church leaders by limiting their powers and establishing procedures that protect members from being disciplined or losing rights without due process.

- They give our elders protection from being compelled by a civil court to testify regarding information they receive through pastoral counseling, while at the same time giving them guidelines for reporting actual or suspected harm to others.

- They reduce the church's exposure to legal liability by satisfying recently developed legal require­ments, even in areas where we deny that the state has jurisdiction, and by requiring that potential lawsuits will be resolved through Biblical mediation or arbitration rather than through litigation.

Most people would agree that these are worthwhile goals, but some might still be troubled by the amount of detail found in these Bylaws. They might say, "Why can't we live with just a few general rules?" The answer to that question is quite simple: Because we live in a fallen world, we tend to interpret general rules differently and twist them to serve our own selfish ends. Therefore, it is often necessary to develop detailed rules to eliminate the possibility of misunderstandings and mistreatment.

This human need for detailed guidance is clearly reflected in Scripture. Instead of giving us only the two great commandments (love God and love your neighbor), God gave us the Ten Commandments. And he didn't stop there. Realizing our weakness and our sinful tendency to ignore or distort his commandments, God instructed Moses to set forth dozens of detailed laws on how we should behave (see Exodus, Leviticus, and Deuteronomy). All of these laws are summed up in the two great commandments, but even Jesus knew that until the world is renewed, we will still need the helpful guidance of the more detailed moral principles set forth throughout Scripture (see Matthew 5:17--7:6).

One of the places that we sometimes need this kind of detailed guidance is in the church. Scripture does not tell us exactly how to give notice or establish quorums for congregational meetings, what information should remain confidential and what may be shared with others, how long church officers should serve without re-election, or how to dispose of property if a church dissolves. These Bylaws are designed to answer these types of questions, and will hopefully spare us from unnecessary confusion and conflict, help us to act in consistent and respectful ways, and allow us to devote ourselves to the more important matters of God's kingdom.

Trinity Reformed Church is a member congregation of [Evangel Presbytery](https://evangelpresbytery.com), and so operates in conformity with not only these Bylaws, but also the [Book of Church Order](https://bco.evangelpresbytery.com) (BCO) of that governing body. These Bylaws are designed to supplement, but not contradict, provisions in the BCO. At times, they will reference the BCO explicitly; in all cases, on any given matter, a complete understanding of the rules under which we operate will be found by examining both documents.

As you read these Bylaws, we encourage you to look up and study the Bible passages that are cited next to particular provisions. If such study does not answer all of your questions and concerns, please do not hesitate to approach our pastor or one of our elders, who will be happy to talk with you about these Bylaws.