# Preface

## The King and Head of the Church

Jesus Christ, upon whose shoulders the government rests, whose name is called Wonderful, Counselor, the Mighty God, the Everlasting Father, the Prince of Peace; of the increase of whose government and peace there shall be no end; who sits upon the throne of David, and upon His kingdom to order it and to establish it with judgement and justice from henceforth, even forever (Isaiah 9:6--7); having all power given unto Him in heaven and in earth by the Father, who raised Him from the dead and set Him at His own right hand, far above all principality and power, and might, and dominion, and every name that is named, not only in this world, but also in that which is to come, and has put all things under His feet, and gave Him to be the Head over all things to the Church, which is His body, the fullness of Him that filleth all in all (Ephesians 1:20--23); He, being ascended up far above all heavens, that He might fill all things, received gifts for His Church, and gave all offices necessary for the edification of His Church and the perfecting of His saints (Ephesians 4:10--13).

Jesus, the Mediator, the sole Priest, Prophet, King, Savior, and Head of the Church, contains in Himself, by way of eminency, all the offices in His Church, and has many of their names attributed to Him in the Scriptures. He is Apostle, Teacher, Pastor, Minister, Bishop and the only Lawgiver in Zion.

It belongs to His Majesty from His throne of glory to rule and teach the Church through His Word and Spirit by the ministry of men; thus immediately exercising His own authority and enforcing His own laws, unto the edification and establishment of His Kingdom.

Christ, as King, has given to His Church officers, oracles and ordinances; and especially has He ordained therein His system of doctrine, government, discipline and worship, all of which are either expressly set down in Scripture, or by good and necessary inference may be deducted therefrom; and to which things He commands that nothing be added, and that from them naught be taken away.

Since the ascension of Jesus Christ to heaven, He is present with the Church by His Word and Spirit, and the benefits of all His offices are effectually applied by the Holy Ghost.

## Preliminary Principles[^1]

Trinity Reformed Church, in setting forth the form of government founded upon and agreeable to the Word of God, reiterates the following great principles which have governed the formation of the plan:

1\. God alone is Lord of the conscience and has left it free from any doctrines or commandments of men (a) which are in any respect contrary to the Word of God, or (b) which, in regard to matters of faith and worship, are not governed by the Word of God. Therefore, the rights of private judgement in all matters that respect religion are universal and inalienable.

2\. In perfect consistency with the above principle, every Christian Church, or union or association of particular churches, is entitled to declare the terms of admission into its communion and the qualifications of its ministers and members, as well as the whole system of its internal government which Christ has appointed. In the exercise of this right it may, notwithstanding, err in making the terms of communion either too lax or too narrow; yet even in this case, it does not infringe upon the liberty or the rights of others, but only makes an improper use of its own.

3\. Our blessed Savior, for the edification of the visible Church, which is His body, has appointed officers not only to preach the Gospel and administer the Sacraments, but also to exercise discipline for the preservation both of truth and duty. It is incumbent upon these officers and upon the whole Church in whose name they act, to censure or cast out the erroneous and scandalous, observing in all cases the rules contained in the Word of God.

4\. Godliness is founded on truth. A test of truth is its power to promote holiness according to our Savior's rule, "By their fruits ye shall know them" (Matthew 7:20). No opinion can be more pernicious or more absurd than that which brings truth and falsehood upon the same level.

On the contrary, there is an inseparable connection between faith and practice, truth and duty. Otherwise it would be of no consequence either to discover truth or to embrace it.

5\. While, under the conviction of the above principle, it is necessary to make effective provision that all who are admitted as teachers be sound in the faith, there are truths and forms with respect to which men of good character and principles may differ. In all these it is the duty both of private Christians and societies to exercise mutual forbearance towards each other.

6\. Though the character, qualifications and authority of Church officers are laid down in the Holy Scriptures, as well as the proper method of officer investiture, the power to elect persons to the exercise of authority in any particular society resides in that society.

7\. All Church power, whether exercised by the body in general, or by representation, is only ministerial and declarative since the Holy Scriptures are the only rule of faith and practice. No Church judicatory may make laws to bind the conscience. All Church courts may err through human frailty, yet it rests upon them to uphold the laws of Scripture though this obligation be lodged with fallible men.

8\. If the preceding Scriptural principles be steadfastly adhered to, the vigor and strictness of disciplines will contribute to the glory and well-being of the Church.

Since ecclesiastical discipline derives its force only from the power and authority of Christ, the great Head of the Church Universal, it must be purely moral and spiritual in its nature.