# Bylaws

## 1. Name

The name by which this organization shall be known in law shall be "Trinity Reformed Church of Bloomington, Indiana, Inc." referred to herein as "the Church."

## 2. Constitution

The Constitution of Trinity Reformed Church, which is subject to and subordinate to the Scriptures of the Old and New Testaments, the infallible Word of God, consists of its doctrinal standards set forth in the *Westminster Confession of Faith* (WCF), together with the *Larger and Shorter Catechisms*, all as adopted by the Board of Elders;[^2] the *Apostles' Creed*, *Nicene Creed*, *Chalcedonian Creed*, and *Athanasian Creed*; and the *Book of Church Order (BCO) of Evangel Presbytery* and any amendments thereto from time to time ("Book of Church Order"). Whenever these Bylaws and the BCO conflict, the BCO controls.

Whenever possible, these Bylaws shall be interpreted so as to be consistent with the Constitution as defined above. Freedom of conscience in the area of baptism (adult-believer baptism or paedobaptism) is guaranteed to the members, officers, and pastors of the Church.

In addition, the Constitution of the Church shall consist of the Book of Church Order of Evangel Presbytery and any amendments thereto from time to time ("Book of Church Order"). Whenever the Church Bylaws and the Book of Church Order conflict, the Book of Church Order controls; however, the Church retains the perpetual right to withdraw from Evangel Presbytery by the affirmative vote of two-thirds (2/3) of voting members present at a congregational meeting specially called for that purpose. One-fourth (1/4) of the voting members on the rolls of the Church shall constitute a quorum at such a meeting.

## 3. Organization and Incorporation

The organization shall be organized as a nonprofit corporation under the laws of the State of Indiana.

## 4. Purpose and Limitations

The purposes of the Church are:

a.  To bring glory and honor to the triune God by promoting true worship, mutual edification, and gospel witness;
b.  To operate exclusively for religious, charitable, and educational purposes within the classifica­tion of legal charities; and no part of the net earnings of the organization shall inure to the benefit of any private stockholder or individual; and no substantial part of the activities of the organization, or any receipt of its funds, shall be utilized for any other purpose except those purposes mentioned above;
c.  To handle affairs pertaining to property and other temporal matters as required by the civil authorities.
    
The Church shall not have or issue shares of stock, and no dividends shall be paid. The Church is prohibited from lending money to guarantee the obligation of a member or officer of the Church. No member or officer of the Church has any vested right, interest, or privilege in or to the assets, property, functions, or activities of the Church. The Church may contract in due course, for reasonable consideration, with its members or officers without violating this provision.

## 5. Location of Office

The registered office of the Church shall be located within Indiana at the address of the Church's registered agent. The Board of Directors (also known as the Board of Elders) or a majority of the members may change the registered agent and the address of the registered office from time to time, upon filing the appropriate statement with the Indiana Secretary of State.

## 6. Membership

a.  The membership shall consist of all communicant, non-communicant, and associate members, all of whom have the privilege of pastoral oversight, instruction, and government by the Church. Com­mun­icant members are those who have been baptized, have made a credible profession of faith in Christ, and have been received into membership as provided in Section 6.b. Non-communicant members are the children of communicant members. Associate members are those believers temporarily residing in a location other than their permanent homes. Such believers may become associate members without ceasing to be members of their home Churches. An associate member shall have all the rights and privileges of communicant members with the exception of voting in a congregational meeting and holding office in the Church.

b.  Parents or sponsors of minor children who become members will sign the Membership Commitment Form along with the minor children. These parents and sponsors must themselves be members in good standing of the Church. When these children reach the age of eighteen, they shall meet with an Elder or Pastor of the Church and, as a testimony to their continued confession, re-sign the Membership Commitment as adults.

c.  A person may be received into membership by confession or reaffirmation of faith. Reception into membership may also be by a letter of transfer from another church in Evangel Presbytery, or by letter of transfer from a church of like faith and practice approved by the Board of Elders. In order to be received into membership, a person must complete the membership course, submit a Membership Application, sign a Membership Commitment, and be accepted by the Session (Board of Elders). The requirement to complete the membership course may be waived at the discretion of the Board of Elders. For an already baptized person who has not made a profession of faith, membership as a communicant is effective upon affirmative vote of the Session to accept the new member. For a person who has not been baptized, membership as a communicant is effective upon his baptism, which ordinance follows the Session's vote to accept the new member.

d.  Voting members of the congregation shall be only those communicant members who are at least eighteen years old and in good standing in the Church. ("Good standing" means that a member is not presently under the censure of suspension or deposition.) Any voting member in attendance at a duly called meeting shall be entitled to one vote on matters brought before the congregation. Voting by proxy shall not be permitted.

e.  Members may be removed from membership at their own request by informing the Board of Elders of their intention to withdraw and the reasons therefore. If a member requests to withdraw because of specific problems or disappointments with the Church, the Board of Elders shall attempt to resolve those matters so that the member may remain in the Church and enjoy greater fruitfulness and personal spiritual growth. If the Board of Elders is unable to resolve those matters, it shall offer to assist the member in locating a church of like faith and practice that can respond more effectively to his gifts and needs. If it appears to the Board of Elders that a member has requested removal merely to avoid church discipline, that request shall not be given effect until the disciplinary process has been properly concluded (see Matt. 18:12--20; Bylaw §16; Guidelines on Church Discipline).

f.  Members may also be removed from member­ship by order of the Board of Elders when they: persis­tently, over an extended period of time, and without adequate reason absent themselves from the stated services of the Church; unite with a church of another denomination; cannot be found for a period greater than one year; or are removed by excommunication for persistent impenitence (see Bylaw §16; Guidelines on Church Discipline). Non-communicant members may be removed from membership with their parents or when they reject the covenantal responsibility of submission to home or Church and neglect the ongoing exhort­a­tion of the Board of Elders to profess faith in Christ.

## 7. Elders and Deacons

a.  Elders and Deacons must be male voting members (and meet Biblical qualifications). In order to be eligible for confirmation, a man shall have been a member in good standing in the Church for at least one year, shall have received appropriate training under the direction or with the approval of the Board of Elders, and shall have served the Church in functions requiring responsible leadership.

b.  Elders, individually and jointly with the Pastors, are to lead the Church in the service of Christ. They are to watch diligently over the people committed to their charge to prevent corruption of doctrine or morals. Evils that they cannot correct by private admoni­tion they should bring to the notice of the Board of Elders. They should visit the people, especially the sick, instruct the ignorant, comfort the mourning, and nourish and guard the children of the covenant. They should pray with and for the people. They should have particular concern for the doctrine and conduct of the Pastors and help them in their labors.

c.  Deacons shall show forth the compassion of Christ in a manifold ministry of mercy toward the saints and strangers on behalf of the Church. As delegated and directed by the Board of Elders, they shall minister to the temporal needs of members and friends, and shall keep in proper repair the Church edifice and other buildings and all physical property belonging to the congregation.

d.  The Board of Elders reserves the right to limit the number of men for each office as they deem to be in the best interest of the Church. Any voting member may propose to the Board of Elders nominations for the offices of Elder and Deacon. The Board of Elders shall certify those nominees whom, upon examination, it judges to possess the neces­sary qualifications for office. An Elder or Deacon who had been previously certified but who resigned from or was divested of the office must be re-certified. At least 30 days preceding the date appointed for the confirmation, the Board of Elders shall announce to the Church in writing the names of those it has certified and recommended for confirmation. This will allow anyone who has serious reservations about any nominee to approach the Board of Elders for reconsideration. Confirmation shall be from those recommended by the Board of Elders­. Vot­ing on the confirmation of Elders and Deacons shall be done by secret ballot, and each vote shall be cast either in favor of or against the confirmation of each candidate, and those candidates receiving the vote of two-thirds (2/3) in favor of their confirmation shall be deemed elected. Elders and Deacons shall be elected for three-year terms of service. The term of service for either a newly-elected or reactivated Elder or Deacon shall begin at the beginning of the calendar year following his election by the congregation. He shall attend meetings of the Board of Elders or Board of Deacons between the time of his election and the subsequent January stated meeting in an ex officio capacity. The terms of Elders and Deacons who are rotating off their respective Boards shall end on December 31 of the appropriate year. If an Elder or Deacon is elected at a meeting other than the annual congregational meet­ing, his regular term shall expire at the time of the second annual congregational meeting following his confirmation. Any Elder or Deacon who has served two consecutive terms must take a one-year sabbatical before serving again in that particular office.

e.  If a ruling Elder or Deacon should lose the confidence of his flock and become unacceptable to a majority thereof, the Church he serves may, by majority vote at a regularly called congregational meeting, request the Session to dissolve the official relationship between the Church and the officer without censure. The Session, after conference with the ruling Elder or Deacon, and after careful consideration, may use its discretion as to dissolving the official relationship. In either case the Session shall report its action to the congregation. If the Session fails or refuses to report to the congregation within sixty (60) days from the date of the congregational meeting or if the Session reports to the congregation that it declined to dissolve such relationship, then any member or members in good standing may file a complaint against the Session in accordance with the provisions of BCO 46.

    An officer may also resign from his office, likewise without censure. In the case of an offense in doctrine or practice, he may also be divested of his office by church disciplinary procedures.

## 8. Pastor

a.  It is the charge of the Pastor to feed and tend the flock as Christ's Minister and with the other Elders to lead them in all the service of Christ. It is his task to conduct the public worship of God; to pray for and with Christ's flock as the mouth of the people unto God; to feed the flock by the public reading and preaching of the Word of God, according to which he is to teach, convince, reprove, exhort, comfort, and evangelize, expounding and applying the truth of Scripture with ministerial authority, as a diligent workman approved by God; to administer the sacraments; to bless the people from God; to shepherd the flock and minister the Word according to the particular needs of groups, families, and individuals in the congregation, catechizing by teaching plainly the first principles of the oracles of God to the baptized youth and to adults who are yet babes in Christ, visiting in the homes of people, instructing and counseling individuals, and training them to be faithful servants of Christ; to minister to the poor, the sick, the afflicted, and the dying; and to make known the gospel to the lost.

b.  If the congregation chooses to elect an Associate Pastor, his relationship to the Church shall be determined by the congregation. If the Board of Elders calls an Assistant Pastor, his relationship with the Church shall be determined by the Board of Elders. The assistant and Associate Pastors shall assist the Senior Pastor in fulfilling the duties assigned to him in Section 8.a., and shall be under his supervision and authority as head of staff by virtue of his office.

c.  The Pastor and Associate Pastor shall be elected by the congregation as follows:
    (1) The Session shall appoint a pulpit committee which may be composed of male members from the congregation at large or the Session, or a mixture of Session members and male members at large. This pulpit committee shall be charged both with presenting pastoral candidates to the Session, and with providing for the ministry of the Word to the congregation during the committee's search process. If the pulpit committee is not identical with the Session, invitations to preach to the congregation shall be issued only with the approval of the Session.
    (2) The pulpit committee shall, after consultation and deliberation, recommend to the Session a pastoral candidate who, in its judgment, fulfills the Constitutional requirements of that office and is most suited to be profitable to the spiritual interests of the congregation. The Session, once it receives the candidate recommended by the pulpit committee, shall order a congregational meeting to convene to vote on the presented candidate; it shall, however, always be the duty of the Board of Elders to convene the congregation in accordance with Bylaw §11 and to conduct the meeting in accordance with that Section. In particular, the congregation should elect a Minister or Ruling Elder of Evangel Presbytery to preside, but if this be infeasible, they may elect any male member of that church.
    (3) When the meeting has been convened with prayer, the Moderator shall give an exhortation to the congregation suited to the purpose of its coming together. The Moderator shall then put the question, "Are you ready to proceed to the election of a Pastor?" If the members declare themselves ready, the Moderator shall call for the nomination.
    (4) If the vote is unanimous or nearly so, a call shall be drawn in due form. If there is a sizeable minority, the Moderator shall address the congregation seeking to persuade the minority to concur in the call. A ballot shall then be taken to determine the number concurring in the call. If there is still a sizeable minority unwilling to concur, the Moderator shall advise the majority and the minority concerning their mutual responsibilities. A final ballot shall then be taken, and if a majority shall insist on prosecuting the call, the Moderator shall proceed to draft a call in due form, and to have it subscribed by the electors, certifying at the same time in writing the number of those who do not concur in the call, and any facts of importance, all of which proceedings shall be laid before the Presbytery, together with the call.
    If at any point in the meeting the congregation decides not to call a Pastor, it may refer the matter back to the pulpit committee, or to the Board of Elders, as the case may be, for report to a later meeting, or take such other action as may be appropriate.
    (5) Please refer to BCO 22.6 for the form of call.
    (6) The Moderator shall certify as to the validity of the meeting of the congregation and that the call as presented has been prepared in all respects as directed by the vote of the congregation.
    (7) All other steps pertaining to the prosecuting of a call to a Pastor shall proceed according to the Evangel Presbytery Book of Church Order, Chapter 22.

d.  Associate and Assistant Pastors shall serve as ex officio members of the Board of Elders and Deacons, having voice but no vote.

e.  The Pastor may resign his position upon thirty days' written notice. Such resignation must be tendered to the Presbytery, and the Church's commissioners shall then show cause, if there be any, why the Presbytery should not accept the resignation. Further process shall then be taken by the Presbytery as described in the Evangel Presbytery BCO 25.1.

f.  If a significant portion of the congregation believes that the Pastor's services are no longer edifying to the congregation, and if private efforts to remedy the situation are unsuccessful, the ministerial relationship may be dissolved as follows: 
    (1) A special congregational meeting shall be called as provided in the Bylaw on congregational meetings;
    (2) Those requesting the Pastor's resignation shall be allowed to state the reasons for their request, and the Pastor shall be given the opportunity to respond, as shall other members of the Church;
    (3) The meeting shall be adjourned to a time not sooner than one week later and not later than two weeks later;
    (4) At the next congregational meeting, further appropriate debate shall be allowed, and a vote shall be taken;
    (5) Upon a two-thirds (2/3) vote in favor of dissolution, the Church's commissioners shall present its request and cause for dissolution to the Presbytery (see Evangel Presbytery BCO 25.1);
    (6) If the ministerial relationship is dissolved, the Church shall provide the Pastor with at least six months severance pay, and shall consider providing such other assistance as is necessary for his needs and the needs of his family while he seeks other employment.

## 9. Board of Elders (Board of Directors)

a.  The Board of Elders is the governing body (Board of Directors) of the Church and consists of its Senior Pastor, active Ruling Elders, and, ex officio, Associate and Assistant Pastors. The Board of Elders shall have the power and authority to make rules and regulations not inconsistent with the laws of the State of Indiana, the Constitution, and these Bylaws. The Board of Elders shall manage the business affairs of the corporation, oversee all matters concerning the conduct of public worship, and it shall concert the best measures for promoting the spiritual growth and evangel­istic witness of the congregation. It shall receive, dismiss, and exercise discipline over the members of the Church, supervise the activities of the Board of Deacons and all other organizations of the congregation, and have final authority over the use of the Church property.

b.  The Moderator (Chairman) of the Board of Elders shall be the Senior Pastor, who may appoint an acting Moderator to function during his absence. The Board of Elders shall choose its own Clerk (Secretary) annually from among its members. The Board of Elders shall also appoint a treasurer, who must be a voting member of the Church and shall ordinarily be a Deacon. If the Elders appoint a treasurer who is not a Deacon, then the treasurer shall serve as an ex officio member of the Board of Deacons.

c.  The Board of Elders shall have final authority for affairs pertaining to property and other temporal matters as required by civil law for nonprofit corporations. In particular, the Board of Elders shall be responsible for the acquisition and disposition of Church property, which includes the management of its financial resources. Neither the Board of Elders nor its delegates shall have the power to buy, sell, mortgage, pledge or in any manner encumber any Church property worth more than \$50,000, nor to incur any indebted­ness exceeding the sum of \$50,000, unless first authorized to do so at a congregational meeting, either through the adoption of the annual budget or by special action of the congregation. The Board of Elders may delegate to the Board of Deacons or to other communicant members such of these responsibilities as it deems approp­riate.

d.  The Board of Elders shall meet at least quarterly and shall convene at the call of the Moderator, any two members of the Board of Elders, or upon its own adjournment. Either oral or written notice, including the date, time, and place of a meeting, shall be given at least two days before a meeting. If mailed, notice shall be deemed to be effective the day after the letter is postmarked. Notice may be waived either orally or in writing. An Elder's or Pastor's attendance at a meeting waives his right to object to lack of notice or defective notice of the meeting, unless at the beginning of the meeting (or promptly upon arrival), he objects to holding the meeting or transacting business at the meeting, and does not vote for or assent to action taken at the meeting.

e.  A quorum is two Elders, if there are three or more, or one ruling Elder, if there are fewer than three, together with the Pastor. In no case may the Board of Elders conduct its business with fewer than two present who are entitled to vote. When the Church is without a Pastor, the Moderator of the Session shall be either a Minister appointed for that purpose by the Presbytery, or one invited by the Session to preside on a particular occasion. When it is inconvenient to procure such a Moderator, the Session may elect one of its own members to preside. In judicial cases, the Moderator shall be a Minister of the Presbytery to which the Church belongs.

f.  The act of a majority present at a Board of Elders meeting at which a quorum is present (when the vote is taken) shall be the act of the Board of Elders. A Pastor or Elder shall be deemed to have approved of an action taken if he is present at a meeting of the Board of Elders unless:
    (1) he objects at the beginning of the meeting (or promptly upon arrival) to holding it or transacting business at the meeting; or
    (2) his dis­sent or abstention from the action taken is entered in the minutes of the meeting; or
    (3) he did not approve the action and he delivers written notice of dissent or abstention to the presiding officer of the meeting before its adjournment or immediately after adjournment of the meeting.

g.  If at any time there are fewer than three persons on the Board of Elders, the congregation may confirm from the Board of Deacons and, if necessary, from among the voting members, men who will temporarily serve as directors of the Church for the purpose of carrying out any required corporate business. The terms of such temporary directors shall expire when sufficient Elders have been confirmed and ordained to bring the number of the Board of Elders to three or more.

h.  The Board of Elders may meet by means of a conference telephone call or similar communications equipment, provided all persons entitled to participate in the meeting received proper notice of the telephone meeting, and provided all persons participating in the meeting can hear each other at the same time. A member participating in a conference telephone meeting is deemed present in person at the meeting. The Moderator of the meeting may establish reasonable rules as to conducting business at any meeting by phone.

i.  The Moderator shall be the Chairman of the Board of Directors and the principal executive officer (president) of the corporation. While performing his moderatorial duties, the Moderator shall be subject to the control of the Board of Elders, and shall in general supervise and control, in good faith, all of the business and affairs of the Church. The Moderator shall, when present, preside at all meetings of the members and of the Board of Elders, and shall conduct such meetings so as to facilitate free and respectful debate and decision making. The Moderator may sign, with the Secretary or any other proper officer of the Church that the Board of Elders has authorized, corporation deeds, mortgages, bonds, contracts, or other Board of Elders authorized instruments.

j.  The Vice-Moderator (Vice-Chairman), shall perform, in good faith, the Moderator's duties if the Moderator is absent, dies, is unable or refuses to act. If the Vice-Moderator acts in the absence of the Moderator, the Vice-Moderator shall have all of the powers of and be subject to all the restrictions upon the Moderator. If there is no Vice-Moderator or the Vice Moderator is unable or refuses to act, then the Secretary shall perform the moderatorial duties. In any case, the regulations of paragraph 9.e. apply.

k.  The Clerk shall be the Secretary of the Church and shall in good faith:
    (1) create and maintain one or more books for the minutes of the proceedings of the members and of the Board of Elders;
    (2) provide that all notices are served in accordance with these Bylaws or as required by law;
    (3) be custodian of the Church and corporate records;
    (4) subscribe the minutes of all meetings of the members and of the Board of Elders;
    (5) when requested or required, authenticate any records of the Church;
    (6) keep a current register of the post office address of each member; and
    (7) in general perform all duties incident to the office of Secretary and any other duties that the Moderator or the Board of Elders may assign to the Secretary.

l.  The treasurer shall:
    (1) have charge and custody of and be responsible for all funds and securities of the Church;
    (2) receive and give receipts for moneys due and payable to the Church from any source, and deposit all moneys in the Church's name in banks, trust companies, or other deposit­ar­­ies that the Board of Elders shall select;
    (3) submit the books and records to a Certified Public Accoun­tant or other accountant as directed by the Board of Elders; and
    (4) in general perform all of the duties inci­dent to the office of treasurer and any other duties that the Moderator or Board of Elders may assign to the treasurer.
    If required by the Board of Elders, the treasurer shall give a bond for the faithful perfor­mance of the treasurer's duties and as insurance against the misappropriation of funds. If a bond is required, it shall be in a sum and with the surety or sureties that the Board of Elders shall determine.

m.  The Board of Elders may establish such committees as it deems necessary for the work of the Church.

## 10. Board of Deacons

The Board of Deacons shall oversee the ministry of mercy in the Church and shall collect and dis­perse funds for the relief of the needy. Other forms of service for the Church may also be commit­ted to the Deacons. The Board of Deacons shall choose its own officers from its membership, submitting its choice for Moderator to the Session for approval.

## 11. Congregational Meetings

a.  There shall be two annual meetings of the Church each year. One meeting shall be held in May of each year at a date, time, and place to be determined by the Board of Elders for the purpose of adopting an annual budget to begin June 1 of each year and end May 31 of each following year. One meeting shall be held in October at a date, time, and place to be determined by the Board of Elders for the purpose of confirming Elders and Deacons and presenting annual reports and transacting any other business as may come before the meeting.

b.  Special meetings of the Church shall be called at a date and location to be determined by the Board of Elders whenever the Board of Elders deems it to be in the best interests of the Church or when requested in writing to do so by one-fourth (1/4) of the voting members of the Church in good standing.

c.  The date, time, and location of all congregational meetings must be announced orally and in written form at least two (2) Lord's Days prior to the time set for the meeting. The day of the meeting itself may not be counted as one of the two required Lord's Days. (For example, a meeting scheduled for Sunday, October 25 must be announced no later than Sunday, October 11.) If the voting members adjourn any congregational meeting to a different date, time, or place, notice of a new date, time, and place need not be given if the new date, time, and place is announced before adjournment. A member entitled to a notice may waive notice of the meeting (or any notice required by laws of the State of Indiana or these Bylaws) by a written notice signed by the member. The member must send the notice of waiver to the Church (either before or after the date and time stated in the notice) for inclusion in the minutes or filing with the Church records.

d.  The purpose of a meeting shall be announced in advance if it involves: a proposed amendment to the Bylaws or articles of incorporation; the confirmation or removal of officers; the calling or removal of the Pastor or an Associate Pastor; the acquisition or disposition of property worth more than $50,000; the dissolution of the Church; or a question regarding the Church's denominational affiliation. When a meeting is called for the transaction of specific matters of business, no business shall be conducted except that which is stated in the notice.

e.  A member's attendance at a meeting: waives the member's right to object to lack of notice or defective notice of the meeting, unless the member at the beginning of the meeting objects to holding the meeting or transacting business at the meeting; and, waives the member's right to object to consideration of a particular matter at the meeting that is not within the purpose or purposes described in the meeting notice, unless the member objects to considering the matter when it is presented.

f.  One-fourth (1/4) of the voting members shall constitute a quorum at congregational meetings. Unless provided otherwise in these Bylaws, a majority vote of votes cast, a quorum being present, is sufficient to decide any matter.

g.  The Moderator of the Board of Elders (generally the Pastor) shall be the Moderator of congregational meetings by virtue of his office. If it should be infeasible or inexpedient for him to preside, or if there is no Pastor, the Session shall appoint one of their number to call the meeting to order and to preside until the congregation shall elect their presiding officer, who may be a Minister of Evangel Presbytery or any male member of that particular Church.

    A Clerk shall be elected by the congregation to serve at that meeting or for a definite period, whose duty shall be to keep correct minutes of the proceedings and of all business transacted and to preserve these minutes in a permanent form, after they have been attested by the Moderator and the Clerk of the meeting. He shall also send a copy of these minutes to the Session of the Church.

## 12. Church Records

a.  The Board of Elders shall keep the following records:
    (1) minutes of its meetings, including a record of the administration of the sacraments and changes in the membership of the congregation;
    (2) minutes of the meetings of the congregation;
    (3) rolls of the members in the congregation (communicant, non-communicant, and voting), with the dates of their reception;
    (4) resolutions adopted by the Board of Elders;
    (5) appropriate accounting records;
    (6) its articles or restated articles of incorporation and all amendments to them currently in effect; and
    (7) its bylaws or restated bylaws and all amendments to them currently in effect.

b.  A member shall be entitled to inspect and copy, at a reasonable time and location specified by the Board of Elders, any of the Church records described above, provided the Board of Elders finds that the member has a proper purpose and is acting in good faith. The Board of Elders may limit access to any records that contain confidential information about a particular person or persons.

## 13. Biblical Counseling

a.  All Christians struggle with sin and the effect it has on our lives and our relationships (see Rom. 3:23; 7:7--25). Whenever a Christian is unable to overcome sinful attitudes or behaviors through private efforts, God commands that he should seek assistance from other members, and especially from the Pastor and Elders, who have the responsibility of providing pastoral coun­sel­ing and oversight (see Rom. 15:14; Gal. 6:1--2; Col. 3:16; 2 Tim. 3:16--4:2; Heb. 10:24--25; 13:17; James 5:16). Therefore, this Church encourages and enjoins its members to make confession to and seek counsel from each other and especially from our Pastors, Elders, and other pastoral counselors.

b.  We believe that the Bible provides thorough guidance and instruction for faith and life. Therefore, our counseling shall be based on Scriptural principles rather than those of secular psychology or psychiatry. Neither the pastoral nor the lay counselors of this Church are trained or licensed as psycho­therapists or mental health professionals, nor should they be expected to follow the methods of such specialists.

c.  Although some members of the Church work in professional fields outside the Church, when serving as pastoral or lay counselors within the Church they do not provide the same kind of professional advice and services that they do when they are hired in their professional capacities. Therefore, members who have significant legal, financial, medical, or other technical questions should seek advice from independent professionals. Our pastoral and lay counselors shall be available to cooperate with such advisors and help members to consider their advice in the light of relevant Scriptural principles.

## 14. Confidentiality 

a.  The Bible teaches that Christians should carefully guard any personal and private information that others reveal to them. Protecting confidences is a sign of Christian love and respect (see Matt. 7:12). It also discourages harmful gossip (Prov. 16:28; 26:20), invites confes­sion (see Prov. 11:13; 28:13; James 5:16), and encourages people to seek needed counseling (see Prov. 20:19; Rom. 15:14). Since these goals are essential to the ministry of the gospel and the work of this Church, all members are expected to refrain from gossip and to respect the confi­dences of others. In particular, our Pastor and Elders shall carefully protect all information that they receive through pastoral counseling, subject to the following guidelines.

b.  Although confidentiality is to be respected as much as possible, there are times when it is appropriate to reveal certain information to others. In particular, when the Pastors and Elders of this Church believe it is Biblically necessary, they may disclose confidential information to appropriate people in the following circumstances:
    (1) When a Pastor or Elder is uncertain of how to counsel a person about a particular problem and needs to seek advice from other Pastors or Elders in this Church or, if the person attends another church, from the Pastors or Elders of that church (see Prov. 11:14; 13:10; 15:22; 19:20; 20:18; Matt. 18:15--17);
    (2) When the person who disclosed the information or any other person is in imminent danger of serious harm unless others intervene (see Prov. 24:11--12);
    (3) When a person refuses to repent of sin and it becomes necessary to institute disciplinary proceedings (see Matt. 18:15--20 and Bylaw §16) or seek the assistance of individuals or agencies outside this Church (see, e.g., Rom. 13:1--5); or
    (4) When required by law to report suspected child abuse.

c.  Scripture commands that confidential information is to be shared with others only when a problem cannot be resolved through the efforts of a small group of people within the Church (Matt. 18:15--17). Therefore, except as provided in Bylaw §14.b., a Pastor or Elder may not disclose confidential information to anyone outside this Church without the approval of the Board of Elders or the consent of the person who originally disclosed the information. The Board of Elders may approve such disclosure only when it finds that all internal efforts to resolve a problem have been exhausted (see, e.g., 1 Cor. 6:1--8) and the problem cannot be satisfactorily resolved without the assistance of individuals or agencies outside this Church (see, e.g., Rom. 13:1--5).

d.  The Pastors and Elders may, but need not, provide counselees with written notice of these confidentiality provisions, but these provisions shall be in effect regardless of whether such notice is given.

## 15. Conflict Resolution

a.  This Church is committed to resolving in a Biblical manner all disputes that may arise within our body. This commitment is based on God's command that Christians should strive earnest­ly to live at peace with one another (see Matt. 5:9; John 17:20--23; Rom. 12:18; and Eph. 4:1--3) and that when disputes arise, Christians should resolve them according to the principles set forth in Holy Scripture (see Prov. 19:11; Matt. 5:23--25; 18:15--20; 1 Cor. 6:1--8; Gal. 6:1). We believe that these commands and principles are obligatory on all Christians and absolutely essential for the well-being and work of the Church. Therefore, any and all dis­putes in this Church shall be resolved according to Biblical principles, as provided in this Bylaw.

b.  When a member of this Church has a conflict with, or is concerned about the behavior of another member, he shall attempt to resolve the matter as follows:
    (1) The offended or con­cerned person shall prayerfully examine himself and take responsibility for his contribution to a problem (Matt. 7:3--5), and he shall prayerfully seek to discern whether the offense is so serious that it cannot be overlooked (Prov. 19:11; see also Prov. 12:16; 15:18; 17:14; 20:3; Eph. 4:2; Col. 3:13; 1 Pet. 4:8).
    (2) If the offense is too serious to overlook, the offended or concerned person shall go, repeatedly if necessary, and talk to the offender in an effort to resolve the matter personally and privately, having first confessed his own wrongdoing (Matt. 18:15).
    (3) If the offender will not listen and if the problem is too serious to overlook, the offended or concerned person shall return with one or two other people who will attempt to help the parties resolve their differences (Matt. 18:16); these other people may be members or officers of the Church or of Evangel Presbytery, other respected Christians in the community, or trained mediators or arbitrators (conciliators) from a Christian concilia­tion ministry.
    At the request of either party to the dispute, the Church shall make every effort to assist the parties in resolving their differences and being reconciled.

c.  Conflicts involving doctrine or church discipline shall be resolved according to the procedures set forth in the Guidelines on Church Discipline.

d.  Employment disputes shall be resolved according to the procedures set forth in the *Employee Policy Manual* of this Church as adopted by the Board of Elders.

e.  If a dispute arises within the Church or between a member and the Church and cannot be resolved through the internal procedures described above, or through intervention or mediation by Evangel Presbytery, it shall be resolved as follows:
    (1) The dispute shall be submitted to mediation and, if necessary, legally binding arbitration in accordance with the *Rules of Procedure* of the Institute for Christian Conciliation, and judgment upon an arbi­tra­tion award may be entered in any court otherwise having jurisdiction.
    (2) All mediators and arbitrators shall be in agreement with the Constitution and Bylaws of the Church and our basic form of government, unless this requirement is modified or waived by all parties to the dispute. If a dispute involves an attempted revision of the Constitution or Bylaws of the Church or our form of government, the mediators and arbitrators shall be in agreement with those documents as they existed prior to the attempted revision.
    (3) If a dispute submitted to arbitration involves a decision reached by an official judicatory (court or ruling body) of this Church, the arbitrators shall uphold the judicatory's decisions on matters of doctrine and church discipline.
    (4) This Section covers the Church as a corporate entity and its agents, including its pastors, officers, staff, and volunteers with regard to any actions they may take in their official capacities.
    (5) This Section covers any and all disputes or claims arising from or related to church membership, doctrine, policy, practice, counseling, discipline, decisions, actions, or failures to act, including claims based on civil statute or for personal injury.
    (6) By signing the Christian conciliation commitment, members agree that these methods shall provide the sole remedy for any dispute arising against the Church and its agents, and they waive their right to file any legal action against the Church in a civil court or agency, except to enforce an arbitration decision.
    (7) If a dispute or claim involves an alleged injury or damage to which the Church's insurance applies, and if the Church's insurer refuses to submit to mediation or arbitration as described in this Section, either the Church or the member alleging the injury or damage may declare that this Section is no longer binding with regard to that part of the dispute or claim to which the Church's insurance applies.

## 16. Church Discipline

Church discipline shall be carried out according to the Guidelines for Church Discipline as adopted by the Board of Elders.

## 17. Ownership and Distribution of Property

a.  The Church shall hold, own, and enjoy its own personal and real property, without any right of reversion to another entity, except as provided in these Bylaws.

b.  "Dissolution" means the complete disbanding of the Church so that it no longer functions as a congregation or as a corporate entity. Upon the dissolution of the Church, its property shall be applied and distributed as follows:
    (1) All liabilities and obligations of the Church shall be paid and discharged or adequate provision shall be made therefore;
    (2) Assets held by the Church upon con­di­tion requiring return, transfer, or conveyance, which condition occurs by reason of the dissol­ution, shall be returned, transferred, or conveyed in accordance with such requirements;
    (3) Assets received and not held upon a condition requiring return, transfer, or conveyance by reason of the dissolution, shall be transferred or conveyed to one or more domes­tic or foreign corpora­tions, societies, or organizations that qualify as exempt organiza­tions under Section 501(c)(3) of the Internal Revenue Code of 1954 (or the corresponding provi­sion of any future United States Inter­nal Revenue Law), and are engaged in activities sub­stan­tially similar to those of the corpora­tion; this distribution shall be done pursuant to a plan adopted by the Board of Elders, provided that no assets are distributed to any organ­iza­tion governed by a member of the Board of Elders; and
    (4) Any assets not other­wise disposed of shall be disposed of by a court of competent jurisdiction of the county in which the principal office of the corporation is then located, for such purposes and to such organizations as said court shall determine.

## 18. Indemnification of Officers

a.  The Board of Elders may choose to indemnify and advance the Church-related expenses of any officer, employee, or agent of the Church.

b.  Subject to the provisions of paragraph c. of this Section, the Church shall indemnify any Elder or Deacon or former Elder or Deacon of the Church against claims, liabilities, expenses, and costs necessarily incurred by him in connection with the defense, compromise, or settlement of any action, suit, or proceeding, civil or criminal, in which such person is made a party by reason of being or having been an Elder or Deacon, to the extent not otherwise compensated, indemnified, or reimbursed by insurance, if:
    (1) The conduct of the Elder or Deacon was in good faith;
    (2) The Elder or Deacon reasonably believed that his conduct was in the best interests of the Church, or at least not opposed to its best interests; and
    (3) In the case of any criminal proceeding, the Elder or Deacon had no reasonable cause to believe that his conduct was unlawful.

c.  The Church may not indemnify an Elder or Deacon in connection with a proceeding brought against him by or in the right of the Church, in which he was adjudged liable to the Church, or where the Elder or Deacon is charged with receiving an improper personal benefit and he is adjudged liable on that basis.

## 19. Committees

When the Board of Elders deems it advisable, it may designate the Chairman of any committee or working group of the Church. The Chairman of each committee shall appoint members to the committee in consultation with the Board of Elders. Individuals may serve on the committee for three consecutive years. Following such a three-year term, an individual may return to service on a committee only after having taken one year leave of absence from that particular committee. The Senior Pastor, or his designee, is an ex officio member of all committees. All other operations of the committee are to be determined by the current edition of *Robert's Rules of Order*.

## 20. Rules of Order

All meetings of the Church, the Board of Elders, and its various boards and committees shall be conducted pursuant to the latest edition of *Robert's Rules of Order.*

## 21. Amendment of Bylaws

These Bylaws may be amended or repealed only by the affirmative vote of two-thirds (2/3) of the votes cast at a duly-called meeting of the Church called for such purposes.

[^2]: In particular, the American revisions to the WCF as adopted by the Orthodox Presbyterian Church in 1936.