#  Guidelines for Church Discipline

1. Church discipline shall be instituted according to these Bylaws.

2. Mutual accountability and discipline within the Church is commanded by God in Scripture and is one of the most important responsibilities of a true Church of Jesus Christ (see Matt. 18:12--20; Rom. 16:17; 1 Cor. 5:1--13; 2 Cor. 2:5--11; Gal. 2:11--14; Eph. 5:11; 1 Thess. 5:14; 2 Thess. 3:6--15; Tim. 1:20; 5:19--20; 2 Tim. 3:1--5; Titus 3:10; Heb. 10:24--30; 12:5--17; 2 John 7--11; Rev. 3:19).

3. Church (ecclesiastical) discipline is the exercise of that authority that the Lord Jesus Christ has committed to the visible Church for the preservation of its purity, peace, and good order.([1](#excerpt-from-biblical-church-discipline-by-daniel-e.-wray)) All members of the Church, both communicant and non-communicant, are under the care of and subject to the discipline of the Church. The ultimate goal of all discipline is to train Christians to be self-disciplined so that they may share in the holiness of God (see Heb. 12:7--13).

4. Discipline may be either administrative or judicial. Administrative discipline is concerned with the maintenance of good order in the government of the Church in other than judicial cases. Its purpose is to see that all rights are preserved and all obligations are fully discharged. Judicial discipline is concerned with the prevention and correction of offenses, an offense being defined as anything in the doctrine or practice of a member of the Church that is contrary to the Word of God. The purpose of judicial discipline is:
    a. to guard and preserve the honor of God (see Rom. 2:24; 1 Cor. 10:31);
    b. to protect the purity of the Church and to guard other Christians from being tempted, misled, divided, or otherwise harmed (see 1 Cor. 5:6); and
    c. to restore fallen Christians to usefulness to God and fellowship with His Church (see Matt. 18:12--14; 2 Cor. 2:5--11; 7:8--10; Gal. 6:1--2).

5. Discipline involves three components or phases:
    a. God commands all Christians to make every effort, with His help, to discipline themselves and lead godly lives (see Eph. 4:25--5:6; 2 Tim. 1:7; 2 Pet. 1:5--11);
    b. if a Christian fails to discipline himself and is trapped in a sin, God commands other brothers and sisters in Christ to lovingly confront, counsel, and encourage him toward repentance (see Bylaw §15.b; Matt. 18:15--16; Gal. 6:1--2; Col. 3:16; Heb. 10:24--25);
    c. if these personal and informal efforts do not correct an offense, God commands the Church leaders to intervene and exercise their ecclesiastical authority to resolve the matter, protect the Church, and, if possible, restore the offender (see Matt. 18:17--20; 1 Cor. 5:1--13; 2 Tim. 4:2; Heb. 13:17). This third phase, which may be referred to as judicial or formal discipline, involves a judicial proceeding (trial) before the Board of Elders, or their designated representatives. Such a trial shall be carried out according to the following procedures, which are designed to provide due process for the offender and promote a just resolution.

6. When an offense is personal and known only to a few individuals, discipline may not be instituted until there has been a good faith effort to resolve the matter privately and informally, yet a Church Court may judicially investigate personal offenses as if general, when the interests of religion seem to demand it (see Bylaw §15.b and BCO 34:5--6). No charge may be accepted if it is filed more than two years after the commission of the alleged offense, unless it appears that unavoidable impediments have prevented an earlier filing of the charge. Every charge must be submitted to the Board of Elders in writing. A person may be censured for filing a charge that the Board of Elders determines to be without merit (see Deut. 19:16--21).

7. An offense that is serious enough to warrant judicial discipline and a trial is:
    a. an offense in the area of conduct and practice that seriously disturbs the peace, purity, and/or unity of the Church;
    b. an offense in the area of doctrine for a non-ordained member that would constitute a denial of a credible profession of faith as reflected in his membership vows; or
    c. an offense in the area of doctrine for an ordained officer that would constitute a violation of the system of doctrine contained in the Holy Scriptures as that system is set forth in our Constitution (see Bylaw §2).
    When the Board of Elders, or their designated representatives, convenes to determine whether an offense has occurred and to administer censure, it shall be referred to as a "judicatory."

8. Just as a good shepherd will go after a sheep that has wandered from the flock (Matt. 18:12--14; Ezek. 34:4, 8, 16), so shall the Elders and members of this Church seek to restore a wandering member to the Lord through Biblical discipline. Therefore, discipline may be instituted or continued either before or after a member seeks to withdraw from membership if the Board of Elders determines that such discipline may serve to guard and preserve the honor of God, protect the purity of the Church, or restore the wandering member to the Lord (see §4). While the Church cannot force a withdrawing person to remain in this congregation, the Church has the right and the responsibility to encourage restoration, to bring the disciplinary process to an orderly conclusion, and to make a final determination as to the person's membership status at the time withdrawal is sought or acknowledged. In doing so, the Board of Elders, at its discretion, may temporarily suspend further disciplinary proceedings, dismiss any or all charges pending against the accused, or proceed with discipline and pronounce an appropriate censure as provided in Sections 19, 20, and 21.

9. When a charge is laid before the Session, it shall be reduced to writing, and nothing shall be done at the first meeting of the Court, unless by consent of parties, except to appoint a prosecutor, and order the indictment to be drawn, a copy of which, with the witnesses then known to support it, shall be served on the accused, and to cite all parties and their witnesses to appear and be heard at another meeting, which shall not be sooner than ten days after such citation. In drawing the indictment, the times, places, and circumstances should, if possible, be particularly stated, that the accused may have an opportunity to make his defense. It is appropriate that with each citation the Moderator or Clerk call the attention of the parties to the Rules of Discipline and assist the parties to obtain access to them.

10. The citation shall be issued and signed by the Moderator or Clerk, by order and in the name of the Court; he shall also issue citations to such witnesses as either party shall nominate to appear on his behalf. Indictments and citations shall be delivered in person or in another manner providing verification of the date of receipt. Compliance with these requirements shall be deemed to have been fulfilled if a party cannot be located after diligent inquiry or if a party refuses to accept delivery.

11. At the second meeting of the Court the charges shall be read to the accused, if present, and he shall be called upon to say whether he be guilty or not. If he confess, the Court may deal with him according to its discretion; if he plead "not guilty" and take issue, the trial shall be scheduled and all parties and their witnesses cited to appear. The trial shall not be sooner than fourteen (14) days after such citation.

12. Accused parties may plead in writing when they cannot be personally present. If, however, at the second meeting of the judicatory an accused fails to appear without satisfactory reason for his absence, or refuses to plead, he shall again be cited, with a warning that the judicatory will deal with his contumacy, and will proceed with the trial in his absence. The time allowed for the appearance on the citation shall be determined by the judicatory with due consideration for the circumstances.

13. The accused shall be entitled to the assistance of male counsel. Such counsel shall be entitled to present evidence, interview witnesses, interpose objections, and otherwise act in defense of the accused. No professional counsel shall be permitted as such to appear and plead in cases of process in any court; but an accused person may, if he desires it, be represented before the Session by any male communing member of the same particular church. A member of the Court so employed shall not be allowed to sit in judgment in the case. No person shall be eligible to act as counsel who does not affirm the Constitution (see Bylaw §2) of this Church. When proceeding in the absence of the accused, the judicatory shall appoint counsel for the accused, who shall present a case to the judicatory in defense of the accused.

14. Before proceeding to trial, courts ought to ascertain that their citations have been duly served.

15. The judicatory shall ordinarily sit with open doors, and must do so when hearing a charge of heresy. No person shall be deprived of the right to set forth, plead, or offer into evidence the provisions of the Word of God or of the subordinate standards.

16. During the trial, the following order shall be observed:
    a. The Moderator shall solemnly announce from the Chair that the Court is about to pass to the consideration of the cause, and to enjoin on the members to recollect and regard their high character as judges of a Court of Jesus Christ, and the solemn duty in which they are about to engage.
    b. The indictment shall be read, and the answer of the accused heard.
    c. The witnesses for the prosecutor and then those for the accused shall be examined.
    d. The parties shall be heard; first, the prosecutor, and then the accused, and the prosecutor shall close.
    e. The roll shall be called, and the members may express their opinion in the cause.
    f. The judicatory, after deliberation, shall vote on each charge and each specification separately. If the judicatory decides that the accused is guilty, it shall proceed to determine the censure.

17. Evidence received by the judicatory during the trial must be factual in nature. It may be direct or circumstantial. Caution should be exercised in giving weight to evidence that is purely circumstantial.

18. Any person may be a witness in a judicial case if the judicatory is satisfied that he has sufficient competence to make the following affirmation, which is required of all witnesses: "I solemnly swear that by the grace of God I will speak the truth, the whole truth, and nothing but the truth concerning the matters on which I am called to testify." The accused may object to the competency of any witness and to the authenticity, admissibility, and relevancy of any testimony or evidence produced in support of the charge and specifications. The judicatory shall decide on all such objections after allowing the accused to be heard in support thereof. The testimony of one witness shall be insufficient to establish the truth of any specification. If the accused so requests, no witness, unless a member of the judicatory, shall testify in the presence of another witness who is to testify concerning the same specification.

19. In order that the trial may be fair and impartial, the witnesses shall be examined in the presence of the accused, or at least after he shall have received due citation to attend. Witnesses may be cross-examined by both parties, and any questions asked which are pertinent to the issue.

20. On all questions arising in the progress of a trial, the discussion shall first be between the parties; and when they have been heard, they may be required to withdraw from the Court until the members deliberate upon and decide the point.

21. Either party may, for cause, challenge the right of any member to sit in the trial of the case, which question shall be decided by the members of the Court other than the one challenged.

22. Pending the trial of a case, any member of the Court who shall express his opinion of its merits to either party, or to any person not a member of the Court; or who shall absent himself from any sitting without the permission of the Court, or satisfactory reasons rendered, shall be thereby disqualified from taking part in the subsequent proceedings.

23. If a person who has been adjudged guilty refuses or fails to present himself for censure at the time appointed, the judicatory shall cite him to appear at another time. If he does not appear after this citation, the censure may be pronounced in his absence.

24. Minutes of the trial shall be kept by the Clerk, which shall exhibit the charges, the answer, all the testimony, and all such acts, orders, and decisions of the Court relating to the case, as either party may desire, and also the judgment. The Clerk shall, without delay, assemble the Record of the Case which shall consist of the charges, the answer, the citations and returns thereto, and the minutes herein required to be kept. The accused shall be allowed one copy of the minutes at the expense of the judicatory.

25. The following censures may be pronounced by the judicatory:
    a. **Admonition** consists in tenderly and solemnly confronting the offender with his sin, warning him of his danger, and exhorting him to repentance and to greater fidelity to the Lord Jesus Christ.
    b. **Rebuke** is a form of censure more severe than admonition. It consists in setting forth the serious character of the offense, reproving the offender and exhorting him to repentance and to more perfect fidelity to the Lord Jesus Christ.
    c. **Suspension** is a form of discipline by which one is deprived of the privileges of membership in the Church, of office, or of both. It may be for a definite or indefinite time. An officer or other member of the Church while under suspension, shall be the object of deep solicitude and earnest dealing from the Board of Elders and the Church to the end that he may be restored.
    d. **Deposition** is a form of censure more severe than suspension. It consists of a solemn declaration by the judicatory that the offender is no longer an officer of the Church.
    e. **Excommunication**, also referred to as disfellowshipping, is the most severe form of censure and is resorted to only in cases of offenses aggravated by persistent impenitence. It consists of a solemn declaration by a judicatory that the offender is no longer considered a member of the body of Christ.
    
26. Since the Church is a body made up of many parts (see 1 Cor. 12:12--30), what happens to one member of the Church necessarily affects and is of legitimate concern to other members (see Rom. 12:15--16; 1 Cor. 5:1--13; 12:12--30). Therefore, the indefinite suspension, deposition, or excommunication of a member shall be announced to the Church so that its members will be able to pray for, encourage, and exhort the accused as opportunities arise, as well as be on guard against any gossip or divisiveness that might arise from the offense or censure (see 1 Cor. 5:9--11; 2 Thess. 3:6--14; Titus 3:10). The public announcement of censure shall always be accompanied by prayer that God will graciously use the discipline for his own glory, the restoration of the offender, and the edification of the Church. This announcement may be made during a regular worship service, at a special meeting of the congregation, or by letter.

27. If an accused leaves the Church during the disciplinary process or while a censure is still in effect, and if the Board of Elders learns that he is attending another church, the Board of Elders may inform that church that the person is currently under church discipline and may ask that church to encourage the accused to repent of his sin and to be restored to the Lord and to any people whom he has offended. Such communications enhance the possibility that a person may finally repent of his sin, and, at the same time, serve to warn the other church to be on guard against the harm that the accused might do to their members (see Matt. 18:12--14; Rom. 16:17; 1 Cor. 5:1--13; 2 Thess. 3:6--14; 2 Tim. 1:15; 2:16--18; 4:9, 14--15; 3 John 9--10).

28. If a person who has been censured through suspension, deposition, or excommunication comes to repentance, the Church shall warmly and lovingly restore him to fellowship within the body (see Matt. 18:13; Luke 15:11--32). Once the Board of Elders is persuaded that the person has sincerely confessed his wrongs and sought forgiveness from God and the person or persons he offended, it shall announce his restoration. That announcement shall be accompanied by a solemn admonition to the congregation that the restored person's offenses have been forgiven and are not to be held against him or otherwise hinder his fellowship within the Church (see 2 Cor. 2:5--11). When deemed appropriate by the Board of Elders, however, the restored person may be restricted from certain responsibilities within the Church until he has demonstrated the requisite qualities for those responsibilities (see, e.g., 1 Tim. 3:2, 8; Titus 1:6).

------------------

### Excerpt from *Biblical Church Discipline* by Daniel E. Wray {-}

> The modes or types of church discipline vary from the mild to the severe. The following are Biblical:
> 
> a. Admonition -- either private or public (Rom. 15:14; Col. 3:16; 1 Thess. 3:14--15; Titus 3:10,11). The *Oxford English Dictionary* defines "admonish" as "to put (one) in mind *to do* duty; to charge authoritatively, to exhort, to urge (always with a tacit reference to the danger or penalty of failure)." The Scripture (and preaching thereof) is a form of admonition (1 Cor. 10:11). Christians ought to admonish and encourage one another, for example to do good works and to attend the meetings of the Church (Heb. 10:24, 25).
> b. Reprove, rebuke, convince, convict (Matt. 18:15; Eph. 5:11; 1 Tim. 5:20; 2 Tim. 4:2; Titus 1:9, 12; 2:15). The Greek word which is used in the passages just cited is a rich word which means "...to rebuke another with such effectual wielding of the victorious arms of the truth, as to bring him, if not always to a confession, yet at least to a conviction, of his sin...." This word is also used of the Holy Spirit's work in John 16:8, and is found on the lips of the enthroned Christ in Rev. 3:19, where he says: "As many as I love, I rebuke and chasten: be zealous therefore, and repent." Thus, proper rebuke is an act of love. The proper guide in such matters is the Word of God which we are told is "profitable...for reproof" (2 Tim. 3:16).
> c. Excommunication. The description given by our Lord Jesus Christ and the apostle Paul define this final form of discipline: "...if he neglect to hear the Church, let him be unto thee as an heathen and a publican" (Matt. 18:17); "But now, I have written unto you not to keep company, if any man that is called a brother be a fornicator, or covetous, or an idolater, or a railer, or a drunkard, or an extortioner; with such an one no not to eat.... Therefore put away from among yourselves that wicked person" (1 Cor. 5:11,13). Thus this most severe of the forms of discipline excludes the offender from the Church and from all privileges of membership. However, while the person must certainly be excluded from the Lord's Supper, he is not excluded from attendance upon the ministry of the Word preached and taught, for even the non-believers are welcome to the public assemblies (1 Cor. 14:23--25). That this form of discipline is unpleasant and a cause for mourning (1 Cor. 5:2) none would doubt. Nevertheless, this practice has associated with it in the New Testament Christ's own sanction (Matt. 18:18--19). Paul claims this sanction when he writes concerning the Corinthian situation that the man be delivered to Satan (i.e., put back into the world which is Satan's domain), "in the name of our Lord Jesus Christ" and "with the power of our Lord Jesus Christ" (1 Cor. 5:4). He could hardly state more clearly and decisively that our Lord Jesus Christ himself is the authority behind true excommunication.