# Declaration of Doctrine and Policies Concerning Selective Service

**SECTION I**

Contrary to the policies of the United States Military, God's Word requires the principled opposition to women serving in military combat positions.[^3] At her 30th General Assembly (2002) the Presbyterian Church in America adopted the following recommendation from the Ad Interim Study Committee on Women in the Military: "This Assembly declares it to be the Biblical duty of man to defend woman and therefore condemns the use of women as military combatants, as well as any conscription of women into the Armed Services of the United States."[^4] We reaffirm the arguments made in the majority report of that committee and understand the title of that document to be a succinct summary of Scripture's teaching: "Man's Duty to Protect Woman." The following paragraphs from "Man's Duty to Protect Woman" are a concise summary of the Biblical arguments:

First, God the Father wages war in defense of Israel, His Bride; Christ our Savior fights to the Death defending His Bride, the Church; the Holy Spirit calls men as officers to guard and protect His Bride; the duty to protect the Garden of Eden and the warning not to eat of the tree of the knowledge of good and evil was given by God to Adam; husbands protect their wives, not wives their husbands. Thus we are taught the binding nature of man's duty to guard and protect his home and wife.

Second, woman is the weaker sex and part of her weakness is the vulnerability attendant to her greatest privilege---that God has made her the "Mother of all the living." Men are to guard and protect her as she carries in her womb, gives birth to, and nurses her children.

Third, we are to renounce every thought and action which tends towards a diminishment of sexual differentiation since God made it and called it "good" \[e.g., Scripture's injunctions concerning women exercising authority over men (1 Timothy 2), women or men wearing clothing of the opposite sex (Deuteronomy 22:5), sodomy (Leviticus 20:15--16), etc.\] Rather than a stingy attitude which minimizes sexuality's implications, we ought to rejoice in this, His blessing.

We also object to the conscription of women on the following ground: the habitual carrying of an innocent non-combatant---the pre-born child in his mother's womb---into warfare without his informed consent is immoral. Professor Vern Poythress explains:

\...to conscript women is immoral, because it unnecessarily endangers the lives of fetuses. The fact that the commanders and/or conscriptors cannot know with certainty is the problem. Principles like the goring ox and the rail around the roof of houses show that we must not only not be guilty of willfully taking innocent life, but must protect against opening the possibility of accidental taking of life.[^5]

The authors of "Man's Duty to Protect Woman" conclude:

We\...are convinced that the creation order of sexuality places on man the duty to lay down his life for his wife. Women and men alike must be led to understand and obey this aspect of the Biblical doctrine of sexuality, believing that such will lead to the unity and purity of the Church, and to the glory of God. Those who deny this duty, whether in word or action, oppose the Word of God. Taken together, we believe the above arguments provide a clear and compelling Scriptural rationale for declaring our Church's principled opposition to women serving in military combat positions.[^6]

Therefore, Trinity Reformed Church, Bloomington objects to the use of women as military combatants, the conscription of women into the armed forces of the United States[^7] for either combatant or non-combatant positions, and the requirement to register for potential conscription into military service. We refuse to submit to any governmental coercion compelling women to serve in or in any way subject themselves to potential conscription into the armed forces of the United States. Such a refusal to submit is not a violation of the admonition in Romans 13 to obey the civil authorities, because "we must obey God rather than men" (Acts 5:29) when any claim of the civil government contradicts the Word of God. Any civil authority requiring or compelling women to compulsory military service does so in violation of the Word of God, particularly God's doctrine of personhood grounded at the most basic level in the sexual calling He gave each person when He made us either male or female. As Jesus said, "\...from the beginning of creation, God made them male and female" (Mark 10:6).

**SECTION II**

We object to the conscription of any member into the armed forces in the case of warfare that is unjust according to historic Christian criteria for just war. While an individual citizen may not dictate policy to the magistrate, God alone is Lord of the conscience (WCF 20:2), nor may a Christian submit to any governmental coercion compelling service in the armed forces that violates his obligation, in union and consultation with other Christians (Prov. 15:22; Heb. 13:7), to maintain conduct just and honorable, even in war (Micah 6:8; Deut. 20). It is a fundamental and long-standing principle (reinforced in the Uniform Code of Military Justice 16c(1)(c) and 14c(2)(a)(i)) that obligation to obey an order depends on the lawfulness of that order. Moreover, inasmuch as our constitutional document, the *Westminster Confession of Faith*, explicitly limits the work of civil magistrates ("to maintain piety, justice, and peace") (WCF 23:2) and the lawful conditions of warfare ("upon just and necessary occasion"), so we affirm that refusal to submit to government that transgresses those limits is not a violation of Romans 13, because "we must obey God rather than men" (Acts 5:29) when any government compels us to disobey the Word of God.

**SECTION III**

We affirm our government's God-given responsibility to protect her citizens and give thanks to God for those men who serve in the armed forces, doing their part to fulfill that responsibility in obedience to God and His commands.

[^3]: On January 24, 2013, the former Secretary of Defense, Leon Panetta, and the Chairman of the Joint Chiefs of Staff, Army General Martin E. Dempsey, rescinded the policy that women are excluded from combat service (see, http:// archive.defense.gov/news/newsarticle.aspx?id=119098). In January of 2016, Defense Secretary Ash Carter implemented the removal of all sex-based restrictions for women and military service (see https://www.sss.gov/Registration/Women- And-Draft). Since that time congressional legislation has been proposed, but not passed, that would require women to register with the Selective Service System (for example, see, http://archive.defense.gov/news/newsarticle.aspx?id=119098 and https://www.nytimes.com/2016/06/15/us/politics/congress-women-military-draft.html).

[^4]: http://pcahistory.org/pca/aiscwim.html#3

[^5]: http://pcahistory.org/pca/01-278.html

[^6]: http://pcahistory.org/pca/01-278.html

[^7]: Throughout this article our reference to the "armed forces of the United States" intends to include any local, state, national, or international military forces.