on:
  push:
     branches:
       - master
       - main

jobs:
  bookdown:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Setup bookdown environment
        uses: warhornmedia/custom-actions/setup-bookdown@latest

      - name: Build the book
        uses: warhornmedia/custom-actions/build-book@latest

      - name: deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
          BRANCH: gh-pages # The branch the action should deploy to
          FOLDER: _book # The folder the action should deploy
          CLEAN: true # Automatically remove deleted files from the deploy branch
